Analyzing Aggravated Burglaries in Davidson County

In [1]:
import requests
import matplotlib.pyplot as plt
from IPython.display import Image
import pandas as pd
import json

1. A dataset containing details about Metro Nashville Police Department reported incidents is available at 'https://data.nashville.gov/Police/Metro-Nashville-Police-Department-Incidents/2u6v-ujjs'. Make use of the API to find all aggravated burglary incidents that were reported during the six month period from January 1, 2021 through June 30, 2021.

#Read API key using json library

with open('data/nasa.json') as fi:
    credentials = json.load(fi)
    
api_key = credentials['api_key']

#Make and API call

In [14]:
url = 'https://data.nashville.gov/resource/2u6v-ujjs.json'
response = requests.get(url)

In [3]:
#response[:1000]

TypeError: 'Response' object is not subscriptable

In [13]:
#df = pd.read_csv('https://data.nashville.gov/resource/2u6v-ujjs.csv').sort_values('incident_reported', ascending=False)
#df

,primary_key,incident_number,report_type,report_type_description,incident_status_code,incident_status_description,investigation_status,incident_occurred,incident_reported,incident_location,...,weapon_description,victim_number,domestic_related,victim_type,victim_description,victim_gender,victim_race,victim_ethnicity,victim_county_resident,mapped_location
2,20210513823_11,20210513823,D,DISPATCHED,U,UNFOUNDED,Closed,2021-09-30T19:45:00.000,2021-09-30T22:43:00.000,1333 1333,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,B,Non-Hispanic,NON RESIDENT,POINT (-86.772 36.196)
1,20210513835_11,20210513835,D,DISPATCHED,U,UNFOUNDED,Closed,2021-09-30T21:23:00.000,2021-09-30T21:47:00.000,105 105,...,NONE,1,True,I,INDIVIDUAL (18 AND OVER),M,U,Non-Hispanic,RESIDENT,POINT (-86.717 36.263)
3,20210513703_11,20210513703,D,DISPATCHED,U,UNFOUNDED,Closed,2021-09-30T19:38:00.000,2021-09-30T21:39:00.000,109 109,...,NONE,1,True,I,INDIVIDUAL (18 AND OVER),F,W,Non-Hispanic,RESIDENT,POINT (-86.712 36.263)
4,20210513650_11,20210513650,D,DISPATCHED,O,OPEN,Open,2021-09-30T19:22:00.000,2021-09-30T19:57:00.000,OLD MATTHEWS RD,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),F,B,Non-Hispanic,RESIDENT,POINT (-86.79 36.22)
6,20210513609_12,20210513609,D,DISPATCHED,O,OPEN,Open,2021-09-30T18:56:00.000,2021-09-30T19:51:00.000,SHELBY AVE,...,CLUB,2,False,I,INDIVIDUAL (18 AND OVER),M,B,Non-Hispanic,RESIDENT,POINT (-86.76 36.17)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,20210505300_11,20210505300,D,DISPATCHED,O,OPEN,Open,2021-09-26T10:51:00.000,2021-09-26T11:25:00.000,DUE WEST AVE N,...,LETHAL/CUTTING INSTRUMENT,1,False,I,INDIVIDUAL (18 AND OVER),M,B,Non-Hispanic,RESIDENT,POINT (-86.74 36.25)
996,20210505302_11,20210505302,D,DISPATCHED,O,OPEN,Open,2021-09-26T04:00:00.000,2021-09-26T11:15:00.000,OPRY MILLS DR,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,NON RESIDENT,POINT (-86.69 36.2)
998,20210505297_11,20210505297,S,SUSPECT,U,UNFOUNDED,Closed,2021-09-26T11:00:00.000,2021-09-26T11:08:00.000,2106 2106,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,U,Non-Hispanic,NON RESIDENT,POINT (-86.763 36.224)
995,20210505310_11,20210505310,D,DISPATCHED,O,OPEN,Open,2021-09-24T15:00:00.000,2021-09-26T11:00:00.000,4TH AVE N,...,Unarmed,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,NON RESIDENT,POINT (-86.78 36.16)
0,2021260418_11,2021260418,W,WITNESS,O,OPEN,Open,2021-04-14T17:00:00.000,2021-04-21T16:40:00.000,HILLSIDE AVE,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,RESIDENT,POINT (-86.78 36.14)

In [5]:
df['incident_reported']= df['incident_reported'].str.split('T', expand=True)[0]

#reported_incidents=reported_incidents.loc[:,['incident_reported']>2021].head()

In [6]:
df['incident_reported'][0]

'2021-04-21'

In [7]:
df[(df['incident_reported']<='2021-09-01') & (df['incident_reported']>='2021-02-01')]

,primary_key,incident_number,report_type,report_type_description,incident_status_code,incident_status_description,investigation_status,incident_occurred,incident_reported,incident_location,...,weapon_description,victim_number,domestic_related,victim_type,victim_description,victim_gender,victim_race,victim_ethnicity,victim_county_resident,mapped_location
0,2021260418_11,2021260418,W,WITNESS,O,OPEN,Open,2021-04-14T17:00:00.000,2021-04-21,HILLSIDE AVE,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,RESIDENT,POINT (-86.78 36.14)

In [8]:
df['incident_reported'] = pd.to_datetime(df['incident_reported'])

In [9]:
df[(df['incident_reported']<='2021-09-01') & (df['incident_reported']>='2021-02-01')]

,primary_key,incident_number,report_type,report_type_description,incident_status_code,incident_status_description,investigation_status,incident_occurred,incident_reported,incident_location,...,weapon_description,victim_number,domestic_related,victim_type,victim_description,victim_gender,victim_race,victim_ethnicity,victim_county_resident,mapped_location
0,2021260418_11,2021260418,W,WITNESS,O,OPEN,Open,2021-04-14T17:00:00.000,2021-04-21,HILLSIDE AVE,...,NONE,1,False,I,INDIVIDUAL (18 AND OVER),M,W,Non-Hispanic,RESIDENT,POINT (-86.78 36.14)